### ISSUE TITLE
Small Text in PDF

### ISSUE THREAD

**Issue by gracepark** [swinton/pdfify#1]
Hi there! It looks like the text when in the PDF is fairly tiny. I've attached the .md and .pdf file.

[testing_pdfify.pdf](https://github.com/swinton/pdfify/files/667095/testing_pdfify.pdf)

This was the markdown:

```
## Testing pdfify

### TEST
**This is so cool**
  - Thanks **Steve**!

### New UPDATE
  - This is working now!
```

I had an original issue with installing `wkhtmltopdf`, but I was able to fix that by updating the lastest versions of Homebrew, Homebrew-Cask, and all Taps. 

The version of `wkhtmltopdf` I have is{
`wkhtmltopdf 0.12.4 (with patched qt)`

Let me know if there's anything I can test to help out! <3

**Comment by swinton** [comment]
Thanks for the bug report, @gracepark.

Definitely something odd going on here. This is the output I'm getting from that same Markdown:

![](https://www.dropbox.com/s/0gbmwxyj1xo4ktm/Screenshot%202016-12-21%2013.57.42.png?dl=1)

@gracepark, when you run `pdfify`, you should see a line of output like:

```
/var/folders/_q/4594nnj94wb7kll_9hl7tk340000gn/T/tmp.RJ0vJUow/XXXX.html
```

Could you grab that HTML file and upload here? :pray:

Thank you :bow:

**Comment by gracepark** [comment]
@swinton - Yes! I got this:
`/var/folders/bg/73v8k2k101q3tv2m8kb53k3w0000gn/T/tmp.MTORqafg/testing_pdfify.html`

**Comment by swinton** [comment]
> /var/folders/bg/73v8k2k101q3tv2m8kb53k3w0000gn/T/tmp.MTORqafg/testing_pdfify.html

:+1:

Could you copy the contents of that file here? I.e. 

`cat /var/folders/bg/73v8k2k101q3tv2m8kb53k3w0000gn/T/tmp.MTORqafg/testing_pdfify.html | pbcopy` 

and paste here 👍

**Comment by gracepark** [comment]
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="generator" content="pandoc">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
  <title></title>
  <style type="text/css">code{white-space: pre;}</style>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
</head>
<body>
<h1 class="letterhead">
  <svg height="42" width="42" class="octicon octicon-mark-github" viewBox="0 0 16 16" version="1.1" aria-hidden="true">
    <path fill-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0 0 16 8c0-4.42-3.58-8-8-8z">
    </path>
  </svg>
  <span><em>GitHub</em> Professional Services</span>
</h1>
<h2 id="testing-pdfify">Testing pdfify</h2>
<h3 id="test">TEST</h3>
<p><strong>This is so cool</strong></p>
<ul>
<li>Thanks <strong>Steve</strong>!</li>
</ul>
<h3 id="new-update">New UPDATE</h3>
<ul>
<li>This is working now!</li>
</ul>
</body>
</html>
```

@swinton ^ Hope that helps!

**Comment by swinton** [comment]
Some potentially useful things here:

http://blog.gluga.com/2012/05/wkhtmltopdf-font-and-sizing-issues.html

Things to try:

- Set a constant fixed width to your HTML page container with CSS.
- Use the flag --disable-smart-shrinking which disables "the intelligent shrinking strategy" used by WebKit
- Make sure the correct fonts are installed (_Source Sans Pro_ and _Apex New_)
- Make sure your HTML document either specifies the encoding type in a META tag, or  else pass the encoding type explicitly to wkhtmltopdf using the --encoding flag (e.g. --encoding utf-8)

**Comment by swinton** [comment]
The issue was caused by @gracepark's _MAHOOSIVE_ screen, it seems. :smile:

Running pdfify on a smaller screen rectified. [Adding `--print-media-type`](https://github.com/swinton/pdfify/pull/2/files#diff-b5fe8aedd74792dc7a65395d7b389df2R35) fixed it.

**Comment by hectorsector** [comment]
@swinton I experienced this issue, and then it didn't happen anymore, but now it's happening again. I took a hammer to your script and tried all the suggestions in [the blog post](http://blog.gluga.com/2012/05/wkhtmltopdf-font-and-sizing-issues.html) as well as some more I found [from a Google search](https://www.google.com/search?client=safari&rls=en&q=pandoc+font+sizes&ie=UTF-8&oe=UTF-8#q=wkhtmltopdf+tiny+fonts+zoom+size), featuring such diddy's as `--dpi XX`, `--zoom X`, and fixing the HTML container width. DPI and Zoom worked, but I imagine that's inconsistent across machines.

**Comment by swinton** [comment]
@hectorsector could you please make sure you're running the latest version of pdfify, `brew upgrade pdfify`? 🙏

**Comment by hectorsector** [comment]
Yessir 😢 
`Error: swinton/brews/pdfify 0.1.2 already installed`

**Comment by swinton** [comment]
@hectorsector, that's strange.

Could you open [a separate issue](https://github.com/swinton/pdfify/issues/new) in this repo?

If you could include the output from [the `/var/...` file](https://github.com/swinton/pdfify/issues/1#issuecomment-268626319), as @gracepark [did above](https://github.com/swinton/pdfify/issues/1#issuecomment-268626863), that would be most helpful :bow:

🔖  There's also [this (seemingly) related question on StackOverflow](https://stackoverflow.com/questions/40814680/wkhtmltopdf-generates-tiny-output-on-mac/41292561) that I've been monitoring.

**Comment by swinton** [comment]
One more question for you, @hectorsector...

What version of `wkhtmltopdf` are you running (`wkhtmltopdf --version`)?

I see [this issue](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3241), that reports font differences between `0.12.3` and `0.12.4`. I'm running `0.12.3`.

```bash
$ wkhtmltopdf --version
wkhtmltopdf 0.12.3 (with patched qt)
```
